import operator
from typing import Annotated, TypedDict

from app.agents.graph.schemas import (
  AnalystOutput,
  AnalystTask,
  RiskLimits,
  SignalInput,
  SuggestionOutput,
)


class HedgeFundState(TypedDict):
  # user/request input
  input: SignalInput

  # optional risk limits
  risk_limits: RiskLimits | None

  # Node outputs
  suggestion: SuggestionOutput | None

  # analyst tasks
  analyst_tasks: list[AnalystTask]

  # diagnostics
  warning: str | None
  error: str | None

  # analyst outputs
  analyst_outputs: Annotated[list[AnalystOutput], operator.add]

# WorkerState represents the state structure passed to individual analyst worker nodes.
# It contains the specific AnalystTask assigned to the worker and a list of AnalystOutput(s)
# generated by that worker. The analyst_outputs use Annotated with operator.add to allow for
# aggregation of outputs across multiple workers in the graph workflow.

class WorkerState(TypedDict):
  analyst_task: AnalystTask
  analyst_outputs: Annotated[list[AnalystOutput], operator.add]