from __future__ import annotations

from abc import ABC, abstractmethod

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.agents.services.llm import get_llm
from app.rag.core.config import QDRANT_COLLECTION
from app.rag.retrieval.retrieval import QdrantRetrievalService, RetrievalRequest, RetrievedChunk


class GenerationRequest(BaseModel):
  query: str
  symbol: str
  horizon: str = "swing"
  retrieved_chunks: list[RetrievedChunk] = Field(..., description="Retrieved chunks from RAG")
  max_context_chunks: int = Field(5, ge=1, le=30)

class GenerationResponse(BaseModel):
  answer: str
  confidence: float | None = Field(None, ge=0.0, le=1.0, description="Confidence in the answer")
  citations: list[str] = Field(default_factory=list, description="List of citations")
  reasoning: str | None = None

class GenerationService(ABC):
  def __init__(self, llm: BaseChatModel):
    self.llm = llm

  @abstractmethod
  def generate(self, request: GenerationRequest) -> GenerationResponse:
    raise NotImplementedError

class LLMGenerationService(GenerationService):

  @staticmethod
  def _build_context(chunks: list[RetrievedChunk], max_chunks: int) -> str:
    selected = chunks[:max_chunks]
    lines: list[str] = []
    for index, chunk in enumerate(selected, start=1):
      src = chunk.doc_hash or chunk.source_id or f"chunk_{index}"
      lines.append(f"[{index}] source={src}\n{chunk.text}")
    return "\n\n".join(lines)

  @staticmethod
  def _collect_citations(chunks: list[RetrievedChunk], max_chunks: int) -> list[str]:
    selected = chunks[:max_chunks]
    citations: list[str] = []
    for index, chunk in enumerate(selected, start=1):
      src = chunk.doc_hash or chunk.source_id
      if src and src not in citations:
        citations.append(src)
    return citations


  def generate(self, request: GenerationRequest) -> GenerationResponse:
    if not request.retrieved_chunks:
      return GenerationResponse(answer="No chunks provided", confidence=0.0, citations=[], reasoning="Retrieval returned no chunks")

    context_text = self._build_context(request.retrieved_chunks, request.max_context_chunks)
    citations = self._collect_citations(request.retrieved_chunks, request.max_context_chunks)

    system_prompt = (
      "You are a financial rasearch agent. "
      "Use only the information provided in the context to answer the user's question. "
      "If you are not sure about the answer, say 'I don't know'. "
      "Provide a detailed reasoning process for your answer. "
      "Do not invent any information. "
    )

    user_prompt = (
      f"Ticker: {request.symbol}\n"
      f"Horizon: {request.horizon}\n"
      f"Question: {request.query}\n"
      f"Context: {context_text}\n"
      "Return: \n"
      "1) Direct answer to the question\n"
      "2) Short reasoning process for your answer\n"
      "3) Mention uncertiniaty if needed"
    )

    messages = [
      SystemMessage(content=system_prompt),
      HumanMessage(content=user_prompt)
    ]

    response = self.llm.invoke(messages)
    answer_text = str(response.content)

    return GenerationResponse(
      answer=answer_text,
      confidence=None,
      citations=citations,
      reasoning="Generated by LLM from the context provided"
    )

def main() -> None:
  retreival = QdrantRetrievalService(collection_name=QDRANT_COLLECTION)
  chunks = retreival.retrieve(request=RetrievalRequest(query="What were NVIDIA gross margins in Q3 FY25?", top_k=5, sparse_top_k=20, alpha=0.5, filters={"source_name": "nvidia"}))
  
  generation = LLMGenerationService(llm=get_llm())
  response = generation.generate(request=GenerationRequest(query="What were NVIDIA gross margins in Q3 FY25?", symbol="NVDA", horizon="swing", retrieved_chunks=chunks, max_context_chunks=5))

  print(f"Answer: {response.answer}")
  print(f"Confidence: {response.confidence}")
  print(f"Citations: {response.citations}")
  print(f"Reasoning: {response.reasoning}")
if __name__ == "__main__":
  main()